### PR TITLE
Copied over Openshift client code from `openshift-acct-mgt`

### LINKED ISSUE #137: Copy over the code from `openshift-acct-mgt` with minimum changes
The initial version should just copy the entire package and do minimum changes to get the function calls and unit/functional testing to work.

Motivation #114

### PR DESCRIPTION
**Pull request by QuanMPhm**
Closes #137. This is the first step of merging `openshift-acct-mgt` into the coldfront plugin. The client code in `moc_openshift.py` is not used in any way, and will only serve to make code review easier to follow. My plan is that as I modify each function in `coldfront_plugin_cloud/openshift.py` to call the Openshift API directly, I will move over some code from `moc_openshift.py`.

The file will eventually be removed after merging of `openshift-acct-mgt` is complete.

### CODE REVIEW

**Review by knikolla — CHANGES_REQUESTED** [review]
You have a new dependency and should update requirements.

**Comment by knikolla** [comment]
Why do you think adding the entire `moc_openshift` module will make things easier to review rather than just implementing functions one by one?

**Comment by joachimweyl** [comment]
@knikolla what needs to be done to approve this PR?

**Comment by knikolla** [comment]
@joachimweyl Quan's last response seems to imply that he will rework the PR to incorporate my feedback.

**Comment by QuanMPhm** [comment]
@knikolla I should have realized my comment to you sounded more ambiguous than I thought. Since it doesn't make sense to copy over the `moc_openshift` module, I don't believe it would make sense to have an entire PR dedicated to copying over code. Since the approach of this merging process will be to implement each function in `openshift.py` one-by-one, I will close this PR unless you believe there's certain code that should be copied.

**Comment by knikolla** [comment]
> @knikolla I should have realized my comment to you sounded more ambiguous than I thought. Since it doesn't make sense to copy over the `moc_openshift` module, I don't believe it would make sense to have an entire PR dedicated to copying over code. Since the approach of this merging process will be to implement each function in `openshift.py` one-by-one, I will close this PR unless you believe there's certain code that should be copied.

@knikolla you can "copy" code one function at a time if you find it useful. There's certainly stuff that's usable from `moc_openshift`. It just may not need to be copied all that once, or without modifications.

**Comment by QuanMPhm** [comment]
Closing this as it has now been replaced by other merging PRs (#175 )

**Pull request closed without merging**
