### PR TITLE
Avoid interactive prompts during unit tests

### PR DESCRIPTION
**Pull request by larsks**
Always call `initial_setup` with `-f` option to avoid the "Do you want to
proceed?" interactive prompt.

### CODE REVIEW

**Comment by larsks** [comment]
This is failing with:

```
django.core.management.base.CommandError: Error: unrecognized arguments: -f
```

How is it failing in GitHub but not locally? I guess I will need to investigate.

**Comment by larsks** [comment]
It was failing because despite the fact that we were requiring `coldfront>=1.0.4`, we were *only* getting coldfront 1.0.4. I've added a commit that increases the minimum version to 1.1.0 (which is still compatible with `>=1.0.4`, so hopefully that's okay).

**Comment by knikolla** [comment]
1.1.0 is okay (in production we're at 1.1.5)

You did end up linting an entire file with your patch though.

**Comment by larsks** [comment]
> You did end up linting an entire file with your patch though.

Whoops, my bad. Let's fix that.

**Review by knikolla — APPROVED** [review]

**Pull request merged**
