### PR TITLE
updated the new default value for 1 Unit of resource allocation

### PR DESCRIPTION
**Pull request by Milstein**

### CODE REVIEW

**Review by joachimweyl — APPROVED** [review]

**Comment by knikolla** [comment]
@Milstein Looks like some of the tests held some assumptions with regards to the default quotas. Can you please update the tests?

**Comment by joachimweyl** [comment]
@knikolla any thoughts on why it failed the py39-functional test?

**Comment by knikolla** [comment]
@joachimweyl `py39-functional` installs Ceph and RGW to test setting swift quotas. In this case the Ceph installation is failing.

**Review by knikolla — APPROVED** [review]

**Comment by larsks** [comment]
@knikolla do you agree that this failure seems to be outside of our control, so we should just ignore it (and possibly bug report it upstream)?

**Comment by knikolla** [comment]
> @knikolla do you agree that this failure seems to be outside of our control, so we should just ignore it (and possibly bug report it upstream)?

Yes, I'm okay with merging this despite CI failures for now while we work on a fix for the CI. (#122)

**Pull request merged**
